## Numpy - Tipe Data Untuk Array

In [18]:
#memasukan modul yang digunakan 
import numpy as np

In [19]:
#membuat array int dan float
array_int = np.array([2,3,4,5], dtype = np.int32)
array_float = np.array([2,3,4,5], dtype = np.float64)

In [20]:
#melihat hasil array int
array_int

array([2, 3, 4, 5])

In [21]:
#melihat type array_int
array_int.dtype

dtype('int32')

In [22]:
#melihat hasil array float
array_float

array([2., 3., 4., 5.])

In [23]:
#melihat type array float
array_float.dtype

dtype('float64')

In [24]:
#membuat array [2,4,6,8,10]
array1 = np.array([2,4,6,8,10])

In [25]:
#melihat hasilnya
array1

array([ 2,  4,  6,  8, 10])

In [26]:
#melihat type array dengan dtype
array1.dtype

dtype('int32')

In [28]:
#merubah type array dengan astype
#dalam hal ini merubah type array int dengan array float
array1_float = array1.astype(np.float64)

In [29]:
#melihat hasilnya
array1_float

array([ 2.,  4.,  6.,  8., 10.])

In [30]:
#melihat type array 
array1_float.dtype

dtype('float64')

In [31]:
#membuat array float
array_float = np.array([2.33, 3.4, 5.9, 4.23])

In [32]:
#melihat hasilnya
array_float

array([2.33, 3.4 , 5.9 , 4.23])

In [33]:
#melihat type array 
array_float.dtype

dtype('float64')

In [34]:
#merubah array float menjadi array int dengan astype
array_int = array_float.astype(np.int32)

In [35]:
#melihat hasilnya
array_int

array([2, 3, 5, 4])

                    ##Semoga Bermanfaat 
                    ##@Raspiani_