## Numpy - Operasi Aritmatika Pada Array

In [14]:
#memasukan modul yang digunakan 
import numpy as np

In [15]:
#membuat array [2,4,6],[1,3,5]
array1 = np.array([[2,4,6],[1,3,5]])

In [16]:
#membuat array [12,14,16],[13,15,17]
array2 = np.array([[12,14,16],[13,15,17]])

In [17]:
#menjumlahkan array1 dengan array1
array1 + array1

array([[ 4,  8, 12],
       [ 2,  6, 10]])

In [18]:
#melihat isi dari array1
array1

array([[2, 4, 6],
       [1, 3, 5]])

In [19]:
#menjumlahkan array1 dengan array2
array1 + array2

array([[14, 18, 22],
       [14, 18, 22]])

In [20]:
#melihat isi dari array2
array2

array([[12, 14, 16],
       [13, 15, 17]])

In [9]:
#mengurangkan array1 dengan array2
array1 - array2

array([[-10, -10, -10],
       [-12, -12, -12]])

In [21]:
#mengurangkan array2 dengan array2
array2 - array2

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
#perkalian array1 dengan array2
array1 * array2

array([[24, 56, 96],
       [13, 45, 85]])

In [23]:
#pembagian array1 dengan array2
array1/array2

array([[0.16666667, 0.28571429, 0.375     ],
       [0.07692308, 0.2       , 0.29411765]])

In [24]:
#memangkatkan array1 dengan 0.5
array1**0.5

array([[1.41421356, 2.        , 2.44948974],
       [1.        , 1.73205081, 2.23606798]])

                    ##Semoga Bermanfaat 
                    ##@Raspiani_