## Numpy - Latihan Dasar 1

Berikut ini latihan dasar 1 numpy in python 

In [31]:
#memasukan modul yang digunakan
import numpy as np

In [32]:
a = [True, 'True', 1]
b = np.array(a)
print(a)
print(b)

print('='*50)

print(type(a))
print(type(b))

[True, 'True', 1]
['True' 'True' '1']
<class 'list'>
<class 'numpy.ndarray'>


In [33]:
#penjumlahan list hasilnya adalah elemen list yang digabungkan 
l = [1, 2, 3]
print(l + l)

print('='*50)

#penjumlahan array adalah elemen array yang dijumlahkan
a = np.array([1, 2, 3])
print(a + a)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [34]:
#perkalian array adalah elemen array yang digabungkan 
a = [1, 2]
b = np.array(a * 2)
print (b * 2)

[2 4 2 4]


In [35]:
#merubah list [1.0, 'one', True] menjadi array
a = np.array([1.0, 'one', True])
print(a)

['1.0' 'one' 'True']


In [36]:
#memeriksa apakah array heights > 100
heights = np.array([134.0, 142.1, 980.4])
print(heights > 100)

[ True  True  True]


In [37]:
#memeriksa apakah array a > 6 
a = np.array([3, 5, 9, 9])
print(a > 6)

print('='*50)

#mencetak nilai elemen dari hasil memeriksa apakah array a > 6 
print(a[a > 6])

[False False  True  True]
[9 9]


In [38]:
#mencetak nilai elemen dari hasil memeriksa apakah array a < 3
a = np.array([1, 2, 3, 4, 5])
print(a[a < 3])

[1 2]


In [39]:
#mencetak nilai elemen dari hasil memeriksa langsung apakah list a > 10 itu tidak dapat dilakukan 
#Hanya list yang dijadikan array terlebih dahulu yang dapat mencetak hasilnya
a = [10, 40, 20, 30, 40]
print(a[a > 10])

TypeError: '>' not supported between instances of 'list' and 'int'

In [40]:
a =  np.array([1, 2, 3, 4]) #merubah list 1, 2, 3, 4] menjadi array 
b = [2, 4, 6, 8] #list b = [2, 4, 6, 8]
c = a[a > 1] #mencetak nilai elemen dari hasil memeriksa langsung apakah array a > 1 
d = c[0]

print(c)
print(d)

print('='*50)

print(b[d]) #mencetak nilai elemen pertama yang bukan termasuk kedalam elemen array c, dalam hal ini mencetak elemen di list b yang elemennya tidak terdapat di array a

[2 3 4]
2
6


In [41]:
#merubah list menjadi array 
a = np.array([1, 2, 3, 4])

#memeriksa nilai array a dimana a < 3
b = (a < 3)
print(b)

print('='*50)

#mencetak hasil pertama pemeriksaan array a dimana a < 3 
print(b[a[0]])

[ True  True False False]
True


                                    ##Semoga Bermanfaat
                                    ##@Raspiani_