## Numpy - Boolean Indexing 

In [26]:
#memasukan modul yang digunakan 
import numpy as np 

In [27]:
#membuat array state yaitu nama-nama kota 
states = np.array(['NY', 'DC', 'CA', 'NY', 'CA', 'DC', 'NY', 'CA'])

In [28]:
#membuat angka random dengan np.random.randn sebanyak 8 baris 4 kolom 
num = np.random.randn(8,4)

In [29]:
#melihat hasil states
states

array(['NY', 'DC', 'CA', 'NY', 'CA', 'DC', 'NY', 'CA'], dtype='<U2')

In [30]:
#melihat hasil num 
num

array([[ 0.17828873,  0.37025811, -0.4377755 , -0.49291494],
       [ 0.26880349, -0.90472482, -0.41961572,  1.30610439],
       [ 1.37144979, -0.1262595 ,  1.70112735, -0.05323914],
       [-0.72411097, -1.10533013,  0.67675491, -0.5374421 ],
       [ 0.9644027 ,  0.62465197, -0.95914444,  1.27413365],
       [ 0.22438088, -0.3885113 , -2.14704479,  0.75754307],
       [-1.07793654,  0.7593483 ,  1.60475951,  1.91958806],
       [ 1.28813984,  0.99254492, -0.80212429,  1.15087565]])

In [31]:
#melihat ukuran num
num.shape

(8, 4)

In [32]:
#memeriksa states atau nama kota yang sama dengan 'NY' = New York
states == 'NY'

array([ True, False, False,  True, False, False,  True, False])

In [33]:
#melihat nilai num dimana statesnya adalah 'NY'
num[states == 'NY']

array([[ 0.17828873,  0.37025811, -0.4377755 , -0.49291494],
       [-0.72411097, -1.10533013,  0.67675491, -0.5374421 ],
       [-1.07793654,  0.7593483 ,  1.60475951,  1.91958806]])

In [34]:
#melihat nilai num dimana statesnya adalah 'NY' dari kolom kedua sampai kolom terakhir 
num[states == 'NY', 1:]

array([[ 0.37025811, -0.4377755 , -0.49291494],
       [-1.10533013,  0.67675491, -0.5374421 ],
       [ 0.7593483 ,  1.60475951,  1.91958806]])

In [35]:
#melihat nilai num dimana statesnya adalah 'NY' dari kolom kedua sampai kolom ketiga 
num[states == 'NY', 1:3]

array([[ 0.37025811, -0.4377755 ],
       [-1.10533013,  0.67675491],
       [ 0.7593483 ,  1.60475951]])

In [36]:
#melihat nilai num dimana statesnya adalah 'NY' dari kolom pertama menjadi satu array (bentuknya satu baris)
num[states == 'NY', 0]

array([ 0.17828873, -0.72411097, -1.07793654])

In [37]:
#melihat nilai num dimana statesnya adalah 'NY' dari kolom pertama menjadi (bentuk penulisannya satu kolom)  
num[states == 'NY', 0:1]

array([[ 0.17828873],
       [-0.72411097],
       [-1.07793654]])

#### Catatan: 

1. == tanda perbandingan
2. != tanda tidak sama

In [38]:
#melihat isi states yang bukan sama dengan 'NY'
states != 'NY'

array([False,  True,  True, False,  True,  True, False,  True])

In [39]:
#melihat isi states yang bukan sama dengan 'DC'
states != 'DC'

array([ True, False,  True,  True,  True, False,  True,  True])

In [40]:
#melihat nilai num dari states yang sama dengan 'NY'
num[(states == 'NY')]

array([[ 0.17828873,  0.37025811, -0.4377755 , -0.49291494],
       [-0.72411097, -1.10533013,  0.67675491, -0.5374421 ],
       [-1.07793654,  0.7593483 ,  1.60475951,  1.91958806]])

In [41]:
#melihat nilai num dari states yang BUKAN sama dengan 'NY'
#negasi states == 'NY'
num[~(states == 'NY')]

array([[ 0.26880349, -0.90472482, -0.41961572,  1.30610439],
       [ 1.37144979, -0.1262595 ,  1.70112735, -0.05323914],
       [ 0.9644027 ,  0.62465197, -0.95914444,  1.27413365],
       [ 0.22438088, -0.3885113 , -2.14704479,  0.75754307],
       [ 1.28813984,  0.99254492, -0.80212429,  1.15087565]])

#### Catatan: 

1. == adalah tanda perbandingan 
2. ~ adalah tanda negasi 
3. | adalah tanda atau (or)

In [42]:
#melihat hasil states yang sama dengan 'NY' atau 'DC'
#dalam hal ini memeriksa
(states == 'NY') | (states == 'DC')

array([ True,  True, False,  True, False,  True,  True, False])

In [43]:
#memeriksa states yang sama dengan 'NY' atau 'DC'
nydc = (states == 'NY') | (states == 'DC')
nydc

array([ True,  True, False,  True, False,  True,  True, False])

In [44]:
#melihat nilai num dari states yang sama dengan 'NY' atau 'DC'
num[nydc]

array([[ 0.17828873,  0.37025811, -0.4377755 , -0.49291494],
       [ 0.26880349, -0.90472482, -0.41961572,  1.30610439],
       [-0.72411097, -1.10533013,  0.67675491, -0.5374421 ],
       [ 0.22438088, -0.3885113 , -2.14704479,  0.75754307],
       [-1.07793654,  0.7593483 ,  1.60475951,  1.91958806]])

                    ##Semoga Bermanfaat
                    ##@Raspiani_