## Numpy - Membuat Array

Berikut ini langkah-langkah membuat array menggunakan modul numpy 

In [27]:
#memasukan modul yang digunakan
import numpy as np

In [28]:
#membuat list 
x = [2,3,4,5,6]

In [29]:
#merubah list menjadi array
np.array(x)

array([2, 3, 4, 5, 6])

In [30]:
#membuat array_x
array_x = np.array([4,5,6])
array_x

array([4, 5, 6])

In [31]:
#melihat type array_x
type(array_x)

numpy.ndarray

In [32]:
#melihat dimensi array_x dengan ndim
array_x.ndim

1

In [33]:
#melihat ukuran array_x dengan shape
array_x.shape

(3,)

In [34]:
#membuat array 2 dimensi
array_2d = np.array([[2,3,6,8],[1,3,5,7]])
array_2d

array([[2, 3, 6, 8],
       [1, 3, 5, 7]])

In [35]:
#melihat dimensi array_2d dengan ndim
array_2d.ndim

2

In [36]:
#melihat ukuran array_2d dengan shape
array_2d.shape

(2, 4)

In [37]:
#membuat array nol dengan zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
#membuat array nol dengan banyaknya baris 4 dan kolom 7
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [39]:
#membuat array yang bernilai 1 dengan ones
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
#membuat array yang bernilai 1 dengan banyaknya baris 2 dan kolom 6
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
#membuat array kosong dengan empty
array_empty = np.empty((3,3,4))

In [42]:
#melihat dimensi array_empty dengan ndim
array_empty.ndim

3

In [43]:
#melihat ukuran array_empty dengan shape
array_empty.shape

(3, 3, 4)

In [44]:
#melihat hasil array_empty
array_empty

array([[[7.59824717e-312, 1.21540149e-321, 0.00000000e+000,
         0.00000000e+000],
        [1.69119330e-306, 3.16251369e+180, 5.28596632e-085,
         3.28442324e+222],
        [1.05878596e+214, 3.42926683e+169, 6.18057710e+223,
         2.87289952e+257]],

       [[2.87518202e+161, 5.01169012e+217, 4.47303447e-143,
         9.11738623e+276],
        [4.27255699e+180, 8.80088569e+199, 1.16267760e-028,
         8.42244189e+252],
        [6.01409647e+175, 9.06707527e+271, 3.60545185e+227,
         1.11530848e+277]],

       [[1.22813740e+224, 5.82589717e+294, 8.42244189e+252,
         6.01409647e+175],
        [9.06707527e+271, 3.60545185e+227, 3.55455412e+180,
         5.49419094e-143],
        [5.76502240e+228, 2.19965310e-094, 9.97328607e-143,
         6.79769037e-310]]])

In [45]:
#membuat range sebanyak 12 dengan arange 
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
#membuat range dengan arange(nilai awal, batas akhir, kenaikan) = (2,40,5)
np.arange(2,40,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37])

                            ##Semoga Bermanfaat
                            ##@Raspiani_