## Numpy - Fancy Indexing 

In [1]:
#memasukan modul yang digunakan
import numpy as np

In [2]:
#membuat array1 dengan baris sebanyak 12 dan kolom sebanyak 5
array1 = np.empty((12,5))

In [3]:
#membuat perulangan dari 0 sampai 11 untuk dijadikan elemen array
for x in range(12):
    array1[x] = x

In [4]:
#menampilkan hasilnya 
array1

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.]])

In [5]:
#menampilkan array atau baris ketiga, kelima, ketujuh dan kesembilan
array1[[2,4,6,8]]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [6]:
#menampilkan array atau baris ketiga, keempat, kesebelas dan kedua belas
array1[[2,3,10,11]]

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.]])

In [7]:
#menampilkan array atau baris pertama dari belakang
array1[[-1]]

array([[11., 11., 11., 11., 11.]])

In [8]:
#menampilkan array atau baris kedua dan keempat dari belakang 
array1[[-2,-4]]

array([[10., 10., 10., 10., 10.],
       [ 8.,  8.,  8.,  8.,  8.]])

In [9]:
#membuat array2 dengan np.arange(40).reshape((8,5)) dimana baris sebanyak 8 dan kolom sebanyak 5
array2 = np.arange(40).reshape((8,5))

In [10]:
#menampilkan hasilnya
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [11]:
#menampilkan nilai dari baris kedua elemen pertama dan baris ketiga elemen kedua
array2[[1,2],[0,1]]

array([ 5, 11])

In [12]:
#menampilkan nilai dari baris keenam elemen ketiga, baris ketujuh elemen keempat, baris kedelapan elemen kelima
#27 33 39
#27 = (5,2) 33 = (6,3) 39 = (7,4) 
array2[[5,6,7],[2,3,4]]

array([27, 33, 39])

                        ##Semoga Bermanfaat
                        ##@Raspiani_