## Numpy - Indexing dan Slicing Array 2 Dimensi

In [1]:
#memasukan modul yang digunakan
import numpy as np

In [2]:
#membuat array [[2,4,6],[1,3,5],[22,23,24],[13,15,19]]
array2 = np.array([[2,4,6],[1,3,5],[22,23,24],[13,15,19]])

In [3]:
#melihat hasilnya 
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 24],
       [13, 15, 19]])

In [4]:
#melihat dimensi array
array2.ndim

2

In [5]:
#mengakses array pertama 
array2[0]

array([2, 4, 6])

In [6]:
#mengakses array ketiga
array2[2]

array([22, 23, 24])

In [7]:
#mengakses array kedua dari belakang
array2[-2]

array([22, 23, 24])

In [8]:
#mengakses nilai atau elemen kedua dari array pertama 
array2[0][1]

4

In [9]:
#mengakses nilai atau elemen pertama dari array keempat
array2[3][0]

13

In [10]:
#menyimpan array keempat dalam x
x = array2[3]

In [11]:
#melihat hasilnya
x

array([13, 15, 19])

In [12]:
#mengakses elemen pertama array x
x[0]

13

In [13]:
#mengakses nilai atau elemen kedua dari array ketiga 
array2[2][1]

23

In [14]:
#bentuk lain dari mengakses nilai atau elemen kedua dari array ketiga 
array2[2,1]

23

##### Kesimpulan : array2[2][1] = array2[2,1]

In [15]:
#mengakses array kedua sampai ketiga
array2[1:3]

array([[ 1,  3,  5],
       [22, 23, 24]])

In [16]:
#mengakses array ketiga 
array2[2:3]

array([[22, 23, 24]])

In [17]:
#mengakses array pertama sampai array ketiga 
array2[:3]

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 24]])

In [18]:
#melihat semua array
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 24],
       [13, 15, 19]])

In [19]:
#melihat nilai atau elemen kedua sampai akhir dari semua array atau dari array pertama sampai array terakhir
array2[:, 1:]

array([[ 4,  6],
       [ 3,  5],
       [23, 24],
       [15, 19]])

In [20]:
#mengakses nilai atau elemen kedua sampai akhir dari array pertama sampai array kedua 
array2[:2, 1:]

array([[4, 6],
       [3, 5]])

In [21]:
#mengakses nilai atau elemen pertama sampai elemen kedua dari array pertama sampai kedua
array2[:2, :2]

array([[2, 4],
       [1, 3]])

In [22]:
#mengakses nilai atau elemen kedua dari semua array 
#hasilnya dijadikan satu array
array2[:, 1]

array([ 4,  3, 23, 15])

In [23]:
#mengakses nilai atau elemen kedua dari semua array
array2[:, 1:2]

array([[ 4],
       [ 3],
       [23],
       [15]])

In [24]:
#mengganti nilai atau elemen pertama sampai kedua dari array pertama sampai array kedua dengan nilai 122
array2[:2, :2] = 122

In [25]:
#melihat hasilnya
array2

array([[122, 122,   6],
       [122, 122,   5],
       [ 22,  23,  24],
       [ 13,  15,  19]])

                           ##Semoga Bermanfaat
                           ##@Raspiani_