## Numpy - Indexing Array dan Slicing Array 1 Dimensi

In [1]:
#memasukan modul yang digunakan 
import numpy as np

In [2]:
#membuat range sebanyak 14 
array1 = np.arange(14)

In [3]:
#melihat hasilnya
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
#melihat hasil array dengan index 3
array1[3]

3

In [5]:
#membuat array dengan arange(2,35,3)=(nilai awal, batas akhir, kenaikan)
array1 = np.arange(2,35,3)

In [6]:
#melihat hasilnya
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [7]:
#mengakses nilai array indeks keempat
array1[4]

14

In [8]:
#mengakses nilai atau elemen array indeks ketiga dari belakang
array1[-3]

26

In [9]:
#mengakses elemen array dari indeks ketiga sampai ketujuh 
array1[3:7]

array([11, 14, 17, 20])

In [10]:
#merubah nilai elemen array indeks ketiga sampai ketujuh dengan nilai 16
array1[3:7] = 16

In [19]:
#melihat hasilnya
array1

array([  2,   5,   8,  16, 123, 123,  28,  23,  26,  29,  32])

In [12]:
#menslice array
#mengakses array indeks ketiga sampai ketujuh
array_slice = array1[3:7]

In [13]:
#melihat hasil array_slice
array_slice

array([16, 16, 16, 16])

In [15]:
#merubah nilai elemen array indeks ketiga dengan nilai 28
array_slice[3] = 28

In [16]:
#melihat hasilnya
array1

array([ 2,  5,  8, 16, 16, 16, 28, 23, 26, 29, 32])

In [17]:
#merubah nilai elemen array indeks kesatu sampai ketiga dengan nilai 123
array_slice[1:3] = 123

In [18]:
#melihat hasilnya
array1

array([  2,   5,   8,  16, 123, 123,  28,  23,  26,  29,  32])

                    ##Semoga Bermanfaat
                    ##@Raspiani_